class AntialiasAttrib:
    MAuto: int

class VBase4:
    def __init__(self, *args, **kwargs) -> None: ...

class Vec3:
    def __init__(self, *args, **kwargs) -> None: ...

def loadPrcFileData(*args, **kwargs) -> None: ...

class GraphicsOutput:
    RTMCopyRam: int

class Texture:
    pass

class AmbientLight:
    def __init__(self, *args, **kwargs) -> None: ...
    def setColor(self, *args, **kwargs) -> None: ...

class DirectionalLight:
    def __init__(self, *args, **kwargs) -> None: ...
    def setColor(self, *args, **kwargs) -> None: ...

class Point3:
    def __init__(self, *args, **kwargs) -> None: ...

class PNMImage:
    def getXSize(self) -> int: ...
    def getYSize(self) -> int: ...
    def getRamImageAs(self, *args, **kwargs) -> bytes: ...

