class AntialiasAttrib:
    MAuto: int

class VBase4:
    def __init__(self, *args, **kwargs) -> None: ...

class Vec3:
    def __init__(self, *args, **kwargs) -> None: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def length(self) -> float: ...

def loadPrcFileData(*args, **kwargs) -> None: ...

class GraphicsOutput:
    RTMCopyRam: int

class Texture:
    pass

class AmbientLight:
    def __init__(self, *args, **kwargs) -> None: ...
    def setColor(self, *args, **kwargs) -> None: ...

class DirectionalLight:
    def __init__(self, *args, **kwargs) -> None: ...
    def setColor(self, *args, **kwargs) -> None: ...

class Point3:
    def __init__(self, *args, **kwargs) -> None: ...

class PNMImage:
    def getXSize(self) -> int: ...
    def getYSize(self) -> int: ...
    def getRamImageAs(self, *args, **kwargs) -> bytes: ...

class BoundingBox:
    def __init__(self, *args, **kwargs) -> None: ...
    def getMin(self) -> Vec3: ...
    def getMax(self) -> Vec3: ...
    def setMinMax(self, min_pt: Vec3, max_pt: Vec3) -> None: ...

class BoundingSphere:
    def __init__(self, *args, **kwargs) -> None: ...
    def getRadius(self) -> float: ...
    def setCenter(self, center: Vec3) -> None: ...
    def setRadius(self, radius: float) -> None: ...

