class Actor:
    def __init__(self, *args, **kwargs) -> None: ...
    def reparentTo(self, *args, **kwargs) -> None: ...
    def setColor(self, *args, **kwargs) -> None: ...
    def controlJoint(self, *args, **kwargs): ...
    def update(self) -> None: ...
    def getJoints(self): ...
    def getAnimNames(self): ...
    def clearModelNodes(self) -> None: ...
    def flattenStrong(self) -> None: ...
    def setHpr(self, *args, **kwargs) -> None: ...
    def setH(self, *args, **kwargs) -> None: ...
    def getParent(self, *args, **kwargs): ...

