class Parallel:
    def __init__(self, *args, **kwargs) -> None: ...

class Sequence:
    def __init__(self, *args, **kwargs) -> None: ...
    def loop(self) -> None: ...

class LerpHprInterval:
    def __init__(self, *args, **kwargs) -> None: ...

