class ShowBase:
    def __init__(self, *args, **kwargs) -> None: ...
    def setWindowTitle(self, *args, **kwargs) -> None: ...
    def setBackgroundColor(self, *args, **kwargs) -> None: ...
    def run(self) -> None: ...
    @property
    def render(self): ...
    @property
    def camera(self): ...
    @property
    def cam(self): ...
    @property
    def camLens(self): ...
    @property
    def win(self): ...
    @property
    def loader(self): ...
    @property
    def taskMgr(self): ...

